all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
all_joints_names:
- vallecula
- tongueRoot1
- tongueRoot2
- tongueBody1
- tongueBody2
- tongueDorsum1
- tongueDorsum2
- tongueBlade1
- tongueBlade2
- tongueTip1
- tongueTip2
- hyoid
- mandible
- shortTendon
- thyroid1
- thyroid2
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
clahe: true
claheratio: 0.1
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_Ultrasound_4Jan28\Ultrasound_4_AW100shuffle14.mat
dataset_type: default
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: C:\Users\Alan\.conda\envs\dlc_gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mobilenet_v2_1.0_224.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_Ultrasound_4Jan28\Documentation_data-Ultrasound_4_100shuffle14.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: mobilenet_v2_1.0
num_joints: 16
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: C:\Users\Alan\Documents\DLC_AlSw_mirror\Ultrasound_4
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
